### ISSUE TITLE
No use with react-router v4

### ISSUE THREAD

**Issue by varHarrie** [alisd23/mobx-react-router#16]
When I click the `<Link>` to redirect, the url in browser correctly change but nothing happen in  the page.

Here is my code:

```ts
// Root.tsx
import * as React from 'react'
import createBrowserHistory from 'history/createBrowserHistory'
import {Link, Route, Switch} from 'react-router-dom'
import {Provider} from 'mobx-react'
import {Router} from 'react-router'
import {syncHistoryWithStore, RouterStore} from 'mobx-react-router'

const routing = new RouterStore()

const browserHistory = createBrowserHistory()

const history = syncHistoryWithStore(browserHistory, routing)

function PageHome () {
  return (
    <div>
      <h1>home</h1>
      <Link to='/404'>404</Link>
    </div>
  )
}

function Page404 () {
  return (
    <div>
      <h1>404</h1>
      <Link to='/'>home</Link>
    </div>
  )
}

export default class Root extends React.Component<void, void> {
  render () {
    return (
      <Provider routing={routing}>
        <Router history={history}>
          <Switch>
            <Route path='/' exact component={PageHome}/>
            <Route component={Page404}/>
          </Switch>
        </Router>
      </Provider>
    )
  }
}

```

```ts
// index.tsx
import * as React from 'react'
import * as ReactDOM from 'react-dom'
import Root from './Root'
import {AppContainer} from 'react-hot-loader'
import './styles/base.styl'

const render = (Root: any) => {
  ReactDOM.render(
    <AppContainer>
      <Root/>
    </AppContainer>,
    document.getElementById('app')
  )
}

render(Root)

if (module.hot) {
  module.hot.accept('./Root', () => {
    const nextRoot = require('./Root').default
    render(nextRoot)
  })
}

```

**Comment by jayalfredprufrock** [comment]
I have a similar issue w/ react-router v4, only I've been trying hashHistory and memoryHistory. Url successfully updates and the Router store gets updated, but the components never re-render. A page refresh then shows the correct component. If I remove the `syncHistoryWithStore` and pass the history directly to `Router`, everything works as expected.

**Comment by PrapatB** [comment]
I tried `<Router history={routingStore.history}>...</Router>`
instead of `<Router history={history}>...</Router>`
and it worked.

**Comment by Lodin** [comment]
Same problem here. As I can see, the original history from [history](https://github.com/ReactTraining/history) v4.6.1 already has `listen` method, and it is overloaded during the syncronisation in the `syncHistoryWithStore` function.

**Comment by alisd23** [comment]
Sorry been away this last week, will take a look soon - seems odd that this simple case would not work.

**Comment by alisd23** [comment]
Ok I think the issue is fixed, it was an oversight on my part. Changed the `listen` function to `subscribe`, and also I am now mutating the original history object as opposed to returning enhanced history as a completely new reference - which was causing issues too. PR at #18.

**Comment by alisd23** [comment]
Let me know if there's still issues. New version **4.0.1** is now out.

**Comment by wallynm** [comment]
Version 4.0.1 not working with child Routes of react-router 4, the components wont update, already tried with two  applications and still wont work

**Comment by mergebandit** [comment]
I'm still having this issue running **4.0.1**

I'm pulling my router out of props:
```
const { router, result } = this.props
```
calling push:
```
router.push(`/top-results/${result.id}`)
```
and here injecting the router store into the component:
```
inject('router')(observer(TopResult))
```
For reference, here's my store creation:
```
import { RouterStore } from 'mobx-react-router'
import appStores from 'store'

let stores = {
  router: new RouterStore(),
  ...appStores,
}

export default stores
```
And here's where I build my root component:
```
import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'mobx-react'
import createBrowserHistory from 'history/createBrowserHistory'
import { syncHistoryWithStore } from 'mobx-react-router'
import { BrowserRouter as Router } from 'react-router-dom'

import './index.css'
import stores from './config/store'
import RouteConfig from './config/views'

const browserHistory = createBrowserHistory()
const history = syncHistoryWithStore(browserHistory, stores.router)

ReactDOM.render(
  /* Currently having to pass {...stores} as well, so I can just inject('specificStore')
   * instead of always inject('store') and then const { specificStore } = this.props.store
   */
  <Provider store={stores} {...stores}>
    <Router history={history}>
      <RouteConfig />
    </Router>
  </Provider>,
  document.getElementById('root')
)
```

Finally, here's my mobx-devtools output:

![image](https://cloud.githubusercontent.com/assets/22401430/25261223/b2906aa0-2616-11e7-9119-9e62243d3944.png)

**Comment by alisd23** [comment]
Ah, I see the issue. You're using the `browserRouter` at the top level and trying to pass history to it - but that prop doesn't exist. You need to use the more low-level `Router` component from react-router, as shown in the [docs](https://github.com/alisd23/mobx-react-router#usage).

**Comment by Ihatetomatoes** [comment]
I am having similar issue @mergebandit, have you managed to fix the issue?

**Comment by njleonzhang** [comment]
@alisd23 Hi I still encounter this issue, would you please help to check? 
[my-react-starter](https://github.com/njleonzhang/my-react-starter)

**Comment by alisd23** [comment]
Hi @njleonzhang I can't see the code yo uwrote above in the project you linked me. Just make sure you've followed the documentation and exhausted all options. If it still doesn't work and you're sure it's a bug with *this* project (which hasn't been addressed already - like this one), then open an issue. :+1:

**Comment by robksawyer** [comment]
Same issue here with the following dependencies.

```
"devDependencies": {
    "babel-core": "^6.23.1",
    "babel-jest": "^21.0.2",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-async-to-generator": "^6.16.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-register": "^6.26.0",
    "babel-tape-runner": "^2.0.1",
    "css-declaration-sorter": "^2.1.0",
    "css-loader": "^0.28.7",
    "css-mqpacker": "^5.0.1",
    "cssnano": "^3.10.0",
    "del": "^3.0.0",
    "dopl": "^0.2.0",
    "dotenv-webpack": "^1.5.4",
    "enzyme": "^2.9.1",
    "eslint-plugin-flowtype": "^2.36.0",
    "eslint-plugin-import": "^2.7.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "faucet": "^0.0.1",
    "favicons-webpack-plugin": "^0.0.7",
    "file-exists": "^4.0.0",
    "gulp": "^3.9.1",
    "html-webpack-plugin": "^2.30.1",
    "image-webpack-loader": "2.0.0",
    "jest": "^21.1.0",
    "lodash.zipobject": "^4.1.3",
    "markdown-loader": "^2.0.1",
    "mobx-react-devtools": "^4.2.15",
    "mobx-react-form-devtools": "^1.7.2",
    "null-loader": "^0.1.1",
    "packpath": "^0.1.0",
    "postcss-animation": "^0.0.12",
    "postcss-color-alpha": "^2.0.0",
    "postcss-css-variables": "^0.8.0",
    "postcss-cssnext": "^3.0.2",
    "postcss-extend": "^1.0.5",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^2.0.6",
    "postcss-nested": "^2.1.2",
    "postcss-pipeline-webpack-plugin": "^3.0.1",
    "postcss-remove-root": "^0.0.2",
    "postcss-url": "^7.1.2",
    "react-addons-test-utils": "^15.6.2",
    "react-hot-loader": "next",
    "react-test-renderer": "^16.0.0",
    "run-sequence": "^2.1.0",
    "sass-loader": "^6.0.6",
    "static-generator-webpack-plugin": "^3.1.2",
    "style-loader": "^0.13.1",
    "tachyons": "^4.8.1",
    "tachyons-background-overlays": "^1.1.0",
    "tap-dot": "^1.0.5",
    "tap-min": "^1.2.1",
    "tap-webpack-plugin": "^2.0.0",
    "tape": "^4.8.0",
    "to-string-loader": "^1.1.5",
    "url-loader": "^0.5.7",
    "webpack": "^3.5.5",
    "webpack-dev-server": "^2.7.1",
    "webpack-merge": "^4.1.0",
    "webpack-svgstore-plugin": "^4.0.1"
  },
  "dependencies": {
    "add": "^2.0.6",
    "axios": "^0.15.0",
    "classlist-polyfill": "^1.2.0",
    "cloudinary-react": "^1.0.4",
    "dotenv": "^4.0.0",
    "eslint": "^4.7.2",
    "faker": "^3.1.0",
    "font-awesome": "^4.7.0",
    "fs": "^0.0.1-security",
    "http-server": "^0.10.0",
    "i18n-iso-countries": "git+https://git@github.com/robksawyer/node-i18n-iso-countries.git",
    "iso3166-2-db": "^2.1.2",
    "json-loader": "^0.5.7",
    "lazy-route": "^1.0.7",
    "material-ui": "^0.19.2",
    "mobx": "^3.3.0",
    "mobx-react": "^4.3.2",
    "mobx-react-form": "^1.32.2",
    "mobx-react-router": "^4.0.1",
    "moment": "^2.18.1",
    "node-sass": "^4.5.3",
    "node-static": "^0.7.9",
    "numeral": "^2.0.6",
    "package": "^1.0.1",
    "postcss-custom-properties": "^6.1.0",
    "promise-polyfill": "^6.0.2",
    "rand-token": "^0.3.0",
    "react": "^16.0.0",
    "react-cookie": "^2.0.8",
    "react-dom": "^16.0.0",
    "react-draggable": "^3.0.3",
    "react-dropzone": "^4.1.0",
    "react-icon-base": "^2.1.0",
    "react-icons": "^2.2.5",
    "react-image-holder": "^2.0.1",
    "react-loading": "^0.1.4",
    "react-materialui-currency": "git+https://git@github.com/robksawyer/react-materialui-currency.git",
    "react-moment": "^0.6.5",
    "react-notification-system": "^0.2.15",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-select": "^1.0.0-rc.5",
    "react-stripe-checkout": "^2.6.3",
    "react-tap-event-plugin": "^2.0.1",
    "react-tooltip": "^3.3.0",
    "react-user-avatar": "^1.9.0",
    "react-widgets": "^3.4.8",
    "remove": "^0.1.5",
    "resolve-url-loader": "^1.6.0",
    "rfx-core": "^1.5.3",
    "rimraf": "^2.5.4",
    "shortid": "^2.2.8",
    "validatorjs": "^3.13.5",
    "whatwg-fetch": "^1.0.0",
    "yarn": "^1.1.0"
  },
  "jest": {
    "verbose": true
  },
  "engines": {
    "node": "8.0.x",
    "yarn": "0.27.5"
  },
```

**Comment by robksawyer** [comment]
For anyone having this issue, I ended up using `@withRouter` like so in my `App.jsx` and that seemed to do the trick.

```
import { Switch, Route, Link, withRouter } from 'react-router-dom';

@inject('store')
@withRouter
@observer
export default class App extends Component {
...
}
```
